In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])
a.shape

(2, 3)

In [19]:
#Array fundamentals
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [20]:
a[0]

np.int64(1)

In [21]:
a[0] = 10
a

array([10,  2,  3,  4,  5,  6])

In [22]:
a[:3]

array([10,  2,  3])

In [23]:
b = a[3:]
b
b[0] = 40
a

array([10,  2,  3, 40,  5,  6])

In [24]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
a[1, 3]

np.int64(8)

In [26]:
#Array attributes
a.ndim

2

In [27]:
a.shape
len(a.shape) == a.ndim

True

In [28]:
a.size
import math
a.size == math.prod(a.shape)

True

In [29]:
a.dtype

dtype('int64')

In [30]:
#How to create a basic array
np.zeros(2)

array([0., 0.])

In [31]:
np.ones(2)

array([1., 1.])

In [32]:
# Create an empty array with 2 elements
np.empty(2)

array([1., 1.])

In [33]:
np.arange(4)

array([0, 1, 2, 3])

In [34]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [35]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [36]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1])

In [37]:
#Adding, removing, and sorting elements
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [38]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [39]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [40]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [43]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [44]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [45]:
#How do you know the shape and size of an array?
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],
                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [46]:
array_example.ndim

3

In [47]:
array_example.size

24

In [48]:
array_example.shape

(3, 2, 4)

In [49]:
#Can you reshape an array?
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [50]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [54]:
np.reshape(a, (1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

In [55]:
#How to convert a 1D array into a 2D array
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [56]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [57]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [58]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [59]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [60]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [61]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [62]:
#Indexing and slicing
data = np.array([1, 2, 3])

data[1]
data[0:2]
data[1:]
data[-2:]

array([2, 3])

In [63]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [64]:
print(a[a < 5])

[1 2 3 4]


In [65]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [66]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [67]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [68]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [69]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [70]:
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [71]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [72]:
print(a[b])

[1 2 3 4]


In [73]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


In [74]:
#How to create an array from existing data
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [75]:
arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [76]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [77]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [78]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [79]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [80]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [81]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

In [82]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [83]:
b1 = a[0, :]
b1
b1[0] = 99
b1
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
b2 = a.copy()

In [85]:
#Basic array operations
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [86]:
data - ones
data * data
data / data

array([1., 1.])

In [87]:
a = np.array([1, 2, 3, 4])

a.sum()

np.int64(10)

In [88]:
b = np.array([[1, 1], [2, 2]])

In [89]:
b.sum(axis=0)

array([3, 3])

In [90]:
b.sum(axis=1)

array([2, 4])

In [91]:
#Broadcasting
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [92]:
#More useful array operations
data.max()
data.min()
data.sum()

np.float64(3.0)

In [93]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [94]:
a.sum()

np.float64(4.8595784)

In [95]:
a.min()

np.float64(0.05093587)

In [96]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [97]:
#Creating matrices
data = np.array([[1, 2], [3, 4], [5, 6]])
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
data[0, 1]
data[1:3]
data[0:2, 0]

array([1, 3])

In [99]:
data.max()
data.min()
data.sum()

np.int64(21)

In [100]:
data = np.array([[1, 2], [5, 3], [4, 6]])
data
data.max(axis=0)
data.max(axis=1)

array([2, 5, 6])

In [101]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

In [102]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [104]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [105]:
np.ones(3)
np.zeros(3)
rng = np.random.default_rng()  # the simplest way to generate random numbers
rng.random(3)

array([0.34943813, 0.92202765, 0.52875302])

In [106]:
np.ones((3, 2))
np.zeros((3, 2))
rng.random((3, 2))

array([[0.04350006, 0.40515797],
       [0.31343834, 0.31718894],
       [0.59585512, 0.71617897]])

In [108]:
#Generating random number
rng.integers(5, size=(2, 4))

array([[0, 3, 3, 3],
       [0, 0, 2, 4]])

In [109]:
#How to get unique items and counts
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [110]:
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [111]:
unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [112]:
unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [114]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [115]:
unique_values = np.unique(a_2d)
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [116]:
unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [117]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)
print(unique_rows)
print(indices)
print(occurrence_count)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


In [118]:
#Transposing and reshaping a matrix
data.reshape(2, 3)
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [119]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [120]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [121]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

In [122]:
#How to reverse an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [123]:
reversed_arr = np.flip(arr)

In [124]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [125]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [126]:
reversed_arr = np.flip(arr_2d)
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [127]:
reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [128]:
reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [129]:
arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [ ]:
arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)

In [130]:
#Reshaping and flattening multidimensional arrays
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [132]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [133]:
a1 = x.flatten()
a1[0] = 99
print(x)  # Original array
print(a1)  # New array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[99  2  3  4  5  6  7  8  9 10 11 12]


In [134]:
a2 = x.ravel()
a2[0] = 98
print(x)  # Original array
print(a2)  # New array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[98  2  3  4  5  6  7  8  9 10 11 12]
